# Base Model Configuration
base_model: google/medgemma-27b-text-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

model_config:
  pad_token_id: 0

plugins:
  - axolotl.integrations.liger.LigerPlugin
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: false 
liger_cross_entropy: false

val_set_size: 0.05

dataset_prepared_path: ./outputs/last_run_prepared
sample_packing: false 
pad_to_sequence_len: true

chat_template: gemma3
datasets:
  - path: omi-health/medical-dialogue-to-soap-summary
    split: train
    type: chat_template
    field_messages: messages
    message_property_mappings: 
      role: role
      content: content
eot_tokens:
  - "<end_of_turn>"

# More information about below parameters can be found here: https://docs.axolotl.ai/docs/config.html
logging_steps: 1 #How often to show loss, gradient, etc.
num_epochs: 20
micro_batch_size: 4 # Can tune to desired batch size, but will limit max sequence length due to memory constraints
gradient_accumulation_steps: 1
evals_per_epoch: 1
max_grad_norm: 1.0

optimizer: adamw_torch_fused
sequence_len: 128000
learning_rate: 1e-6
adam_beta1: 0.9              # Standard, well-tested value
adam_beta2: 0.999            # Higher beta2 for more stability
adam_epsilon: 1e-8           # Standard epsilon works well with regular AdamW
warmup_ratio: 0.1
weight_decay: 0.01


bf16: true
fp16: false
tf32: false

# FSDP Configuration
fsdp:
  - full_shard
  - auto_wrap

fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_offload_params: true
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: Gemma3DecoderLayer
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_sync_module_states: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_use_orig_params: true
  # activation_checkpointing: true

gradient_checkpointing: offload

save_strategy: epoch
hub_model_id: baseten-admin/Gemma-27B-Finetuned-Full-Context #Where to store the model, need to make one in your account first if your API key has finegrained permissions
hub_strategy: all_checkpoints #How often to store to HF


save_safetensors: false

flash_attention: true
eval_sample_packing: false
sequence_parallel_degree: 16