[project]
name = "ml-cookbook"
version = "0.1.0"
description = "ML Cookbook by the Baseten Training Team"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "truss>=0.14.1",
    "requests>=2.28",
]
